# Spring Datasource Configuration
spring.datasource.url=PASTE_YOUR_NEON_CONNECTION_STRING_HERE
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Fix for Cross-Origin (CORS) when we deploy the frontend later
cors.allowed.origins=*