spring.application.name=demo
# Sets the database file location to a folder named "data" inside your backend directory
spring.datasource.url=jdbc:h2:file:./data/gcetts_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tells Spring to automatically create your database tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Allows you to view the database in your browser at http://localhost:8080/h2-console
spring.h2.console.enabled=true